# Generated by Django 6.0.3 on 2026-05-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0003_alter_inscricao_idade_alter_inscricao_igreja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='alergias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='autoriza_imagem',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='como_conheceu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='doencas_pre_existentes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='medicamentos_continuos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='observacoes_medicas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='parentesco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='participa_igreja',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='pastor_lider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='restricoes_alimentares',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='telefone_lider',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='tempo_igreja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='estado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='tamanho_camisa',
            field=models.CharField(choices=[('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('XG', 'XG')], max_length=5),
        ),
    ]
